config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }
  
  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root :to => 'sales#index'

  resources :permissions
  resources :messages, except: [:new, :edit]
  resources :chats, only: [:show]
  resources :daters do
    resources :favorites, only: [:create, :destroy]
  end

  resource :concierge, only: [:show]

  namespace :concierge do
    resources :dashboard, only: :index
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :daters
    resources :concierges
  end

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  recipient_id :integer
#  body         :string(200)
#  status       :integer          default(0)
#  created_at   :datetime
#  updated_at   :datetime
#

class Message < ActiveRecord::Base

  LIMIT = 1     # number of messages a user may send per day

  belongs_to :user
  belongs_to :recipient, class_name: 'User'

  has_many :permissions # Specifically, it can have up to 2. One for the sender, one for the receiver.

  validates :user_id, presence: true
  validates :recipient_id, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  after_create :set_sender_permission

  after_save :set_recipient_permission

  enum status: [ :queued, :sent, :read, :accepted, :rejected ]
  # 'Queued'  means the man has submitted the message, but it's in the woman's queue.
  # 'Sent'    means it's made it to the woman's inbox, but she hasn't seen it yet.
  # 'Read'    means she's seen it, but hasn't responded.



  def has_been_accepted?
    self.permissions.count == 2 && self.permissions.first.status == 'allowed' && self.permissions.last.status == 'allowed'
  end
  

  private

  # When a message gets sent, we're taking it as implied that the sender is willing to chat with the recipient.
  # We create a Permission object after_create to testify to this.
  def set_sender_permission
    self.permissions << Permission.create({
      user_id:        user_id,
      target_user_id: recipient_id,
      status:         1
    })
  end

  # If the recipient accepts the message, we create a positive permission.
  def set_recipient_permission
    if self.accepted? && self.permissions.find_by(user_id: recipient_id, target_user_id: user_id).nil?
      self.permissions.create(user_id: recipient_id, target_user_id: user_id, status: 1)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  load_and_authorize_resource
  
  # GET /messages
  def index
    @messages = current_user.messages
    # @outbox = current_user.messages_sent.joins(:permissions).order("permissions.created_at DESC")
    # @inbox  = current_user.messages_received.joins(:permissions).order("permissions.created_at DESC")
  end

  # GET /messages/:id
  def show; end

  # POST /messages
  def create
    num_sent_today = current_user.messages_sent.where("created_at >= ?", Time.now.beginning_of_day).count

    @message.save if num_sent_today < Message::LIMIT

    if @message.persisted?
      track_activity @message, params[:action], @message.recipient 
      redirect_to root_path, notice: I18n.t("messages.create.sent")
    else
      redirect_to root_path, alert: I18n.t("messages.create.exceeded_limit")
    end
  end

  # PATCH /messages/:id
  def update
    if params[:message][:status] == "accept"
      response = @message.accepted!
    elsif params[:message][:status] == "reject"
      response = @message.rejected!
    end
    render json: { result: response }
  end

  # DELETE /messages/:id
  def destroy; end


  private

  def message_params
    params.require(:message).permit(:user_id, :recipient_id, :body)
  end

  def reject_params
    params.require(:message).permit(:status)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def outbound?(m)
    current_user === m.user
  end

  def inbound?(m)
    current_user === m.recipient
  end

  def unread?(m)
    m.queued? || m.sent?
  end

  def outbound_and_unread?(m)
    outbound?(m) && unread?(m)
  end

  def direction(m)
    inbound?(m) ? "received" : "sent"
  end

  def get_other_user(m)
    return m.recipient if m.user == current_user
    return m.user if m.recipient == current_user
  end

end

app/views/messages/index.html.erb
<div class="message-wrapper" ng-controller="MessagesController as msg">
  <div class="messages-title-bar">
    <h2>Messages Index</h2>
  </div>
  
  <nav>
    <ul>
      <li ng-class="{selected: msg.viewing === 'received'}" ng-click="msg.viewing = 'received'">Received</li>
      <li ng-class="{selected: msg.viewing === 'sent'}" ng-click="msg.viewing = 'sent'">Sent</li>
      <li ng-class="{selected: msg.viewing === 'all'}" ng-click="msg.viewing = 'all'">All</li>
    </ul>
  </nav>
  <section class="messages-box">
    <table ng-cloak>
      <% @messages.each do |m| %>

        <tr class="inbox-message-row <%= 'unread' if inbound?(m) && unread?(m) %>" ng-if="msg.viewing === '<%= direction(m) %>' || msg.viewing === 'all'">
          <td class="message-dir">
            <% if inbound?(m) %>
              <%= fa_icon 'arrow-right' %>
            <% else %>
              <%= fa_icon 'arrow-left' %>
            <% end %>
          </td>
          <td class="message-thumbnail-cell">
            <% if inbound?(m) %>
              <%= image_tag m.user.primary_profile_photo_thumb, class: "message-thumbnail" %>
            <% else %>
              <%= image_tag m.recipient.primary_profile_photo_thumb, class: "message-thumbnail" %>
            <% end %>  
          </td>
          <td>
            <% if inbound?(m) %>
              <h4 class="user-name"><%= m.user.display_name %> would like to kinect with you</h4>
            <% else %>
              <h4 class="user-name">You have sent a request to <%= m.recipient.display_name %></h4>
            <% end %>  
            
            <p class="message-preview"><%= m.body %></p>
          </td>
          <td class="message-actions">
            <!-- I'm pretty sick of nested 'if' statements, so I'm doing this in a more verbose way -->
            <% if m.has_been_accepted? %>
              <%= link_to fa_icon("comments-o"), chat_path(get_other_user(m)), class: 'interaction-request-button message' %>
            <% elsif outbound?(m) && m.queued? %>
              Message is Queued.
            <% elsif outbound?(m) %>
              Awaiting Reply.
            <% elsif inbound?(m) %>
              <%= form_for m, remote: true do |m| %>
                <div style="display: inline-block; margin: 0;">
                  <button name="message[status]" value="accept" class="interaction-request-button accept"><%= fa_icon("check") %></button>
                </div><div style="display: inline-block"> 
                  <button name="message[status]" value="reject" class="interaction-request-button block"><%= fa_icon("remove") %></button>
                </div>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </section> 

</div>  