config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }
  
  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root :to => 'sales#index'

  resources :permissions
  resources :messages, except: [:new, :edit]
  resources :chats, only: [:show]
  resources :daters do
    resources :favorites, only: [:create, :destroy]
  end

  resource :concierge, only: [:show]

  namespace :concierge do
    resources :dashboard, only: :index
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :daters
    resources :concierges
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_filter :authenticate_user!
  layout 'application_chat'

  def show
    @other_user = User.find(params[:id])
    @contacts = current_user.get_contacts

    # Check if I've blocked or never accepted them
    my_perm = Permission.find_by({
      user_id:        current_user.id,
      target_user_id: @other_user.id,
      status:         1
    })

    # Check if they've blocked or never accepted me
    their_perm = Permission.find_by({
      user_id:        @other_user.id,
      target_user_id: current_user.id,
      status:         1
    })

    @sender = {
      id: current_user.id,
      displayName: current_user.display_name,
      thumg: current_user.primary_profile_photo_thumb
    }
    @receiver = {
      id: @other_user.id,
      displayName: @other_user.display_name,
      thumg: @other_user.primary_profile_photo_thumb
    }

    if my_perm && !their_perm
      redirect_to root_url, alert: I18n.t("flash_messages.chats.show.missing_their_permission")
    elsif their_perm && !my_perm
      # Shouldn't be possible to get to this branch unless they type in the ID in the URL.
      redirect_to root_url, alert: I18n.t("flash_messages.chats.show.missing_my_permission")
    elsif !my_perm && !their_perm
      redirect_to root_url, alert: I18n.t("flash_messages.chats.show.missing_both_permissions")
    end
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
  # Every chat instance needs a unique ID for its data to be stored in firebase.
  # We're going to concatenate their ordered IDs, bridged with an underscore.
  def get_room_id(user1, user2)
    user_ids = [user1.id, user2.id].sort
    user_ids.join("_")
  end
end

app/views/chats/show.html.erb
<div class="full-chat-wrapper" ng-controller="ChatsController as chat" 
  data-sender-id="<%= current_user.id %>" 
  data-sender-name="<%= current_user.display_name %>" 
  data-sender-thumb="<%= current_user.primary_profile_photo_thumb.url %>"
  data-receiver-id="<%= @other_user.id %>" 
  data-receiver-name="<%= @other_user.display_name %>"   
  data-receiver-thumb="<%= @other_user.primary_profile_photo_thumb.url %>"
  data-room-id="<%= get_room_id(current_user, @other_user) %>" 
  data-contacts="<%= current_user.get_contacts.map(&:id) %>" 
  ng-cloak>
  <div class="chat-header">
    <div ng-if="chat.selectedContact">
      <div class="chat-thumbnail">
        <%= link_to dater_path(@other_user) do %>
          <img ng-src="{{chat.selectedContact.thumb}}" ng-class="{online: chat.onlineNow(chat.selectedContact)}">
        <% end %>
      </div>
      <h4>Chat with <%= link_to @other_user.display_name, dater_path(@other_user) %></h4>
      <h5><span am-time-ago="chat.selectedContact.last_seen"></span>&nbsp;&nbsp;•&nbsp;&nbsp;{{chat.messages.length}} messages.</h5>
    </div>
  </div>

  <div class="chat-contents">
    <ul>
      <li class="chat-message" ng-repeat="msg in chat.messages" ng-class="[chat.fromSelf(msg) ? 'mine' : 'theirs']">
        <div class="message-sender">{{msg.sender}}</div>
        <div class="message-time">{{ msg.created_at | date:'h:mma, MMMM d yyyy' }}</div>
        <div class="arrow"></div><div class="chat-message-box pre-wrap">{{msg.message}}</div>
      </li>

      <li class="chat-bottom-spacer"></li>
    </ul>

  </div>

  <div class="chat-send" id="chat-send">
    <form ng-submit="chat.pushMessage()">
      <div class="flex-inputs">
        <div class="textarea-holder">
          <textarea id="chat-message-input" ng-model="chat.current_input" placeholder="Type a message" ng-enter-to-send="chat.hi()"></textarea>
        </div>
        <div class="submit-holder">
          <input type="submit" value="Send" class="interaction-text-button message">
        </div>
      </div>
    </form>
  </div>

  <div class="contact-list-wrapper">
    <h3>Contacts</h3> 
    <ul>
      <li ng-repeat="contact in chat.contacts">
        <a ng-href="/chats/{{contact.$id}}" ng-class="contact.$id == chat.receiverId ? 'selected' : ''">
          <img ng-src="{{contact.thumb}}" alt="" ng-class="{online: chat.onlineNow(contact)}">
          <h4>{{contact.display_name}}</h4>
          <p am-time-ago="contact.last_seen"></p>
        </a>
      </li>
    </ul>
  </div>
</div>