config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }
  
  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root :to => 'sales#index'

  resources :permissions
  resources :messages, except: [:new, :edit]
  resources :chats, only: [:show]
  resources :daters do
    resources :favorites, only: [:create, :destroy]
  end

  resource :concierge, only: [:show]

  namespace :concierge do
    resources :dashboard, only: :index
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :daters
    resources :concierges
  end

end

app/views/layouts/_copyright_notice.html.erb
Copyright © <%= Date.today.year %> Kinected. All Rights Reserved.

app/views/layouts/_flash_messages.html.erb
<div ng-controller="FlashMessagesController as flash" data-initial='<%= flash.to_json.html_safe %>' ng-cloak ng-show="flash.factory.show">
  <div class="flash">
    <div class="close" ng-click="flash.factory.setShow(false)"><%= fa_icon "close" %></div>
    <div class="message">{{flash.factory.message}}</div>
    <div class="background notice" ng-show="flash.factory.show === 'notice'"></div>
    <div class="background alert" ng-show="flash.factory.show === 'alert'"></div>
  </div>
  <div class="flash-spacer" size-spacer-by-flash></div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-spacing"></div>
<footer class="main-footer">
  <div class="line-1">
    <ul>
      <li><%= link_to "About Kinected", id: 'footer-about-link' %></li><li>
      <%= link_to "Our Blog", id: 'footer-blog-link' %></li><li>
      <%= link_to "Contact Us", id: 'footer-contact-link' %></li><li>
      <%= link_to "Sign Out", destroy_user_session_path, id: 'footer-signout-link', method: :delete %></li>
    </ul>
  </div>
  <p class="line-2 light-gray"><%= render partial: 'layouts/copyright_notice' %></p>
</footer>

app/views/layouts/_logged_out_footer.html.erb
<div class="footer-spacing"></div>
<footer class="main-footer">
  <div class="line-1">
    <ul>
      <li><%= link_to "Return Home", root_path %></li><li>
        <%= link_to "Log In", new_user_session_path unless params[:controller] == 'sessions' %>
        <%= link_to "Sign Up", new_user_registration_path unless params[:controller] == 'registrations' %>
      </li>
    </ul>
  </div>
  <p class="line-2 light-gray">Copyright © <%= Date.today.year %> Kinected. All Rights Reserved.</p>
</footer>

app/views/layouts/_main_nav_links.html.erb
<li>
  <%= link_to daters_path, id: 'sidebar-browse-link' do %>
    <span class="nav-text-link">Browse</span><%= fa_icon 'users' %>
  <% end %>
</li>
<li>
  <%= link_to messages_path, id: 'sidebar-messages-link' do %>
    <span class="nav-text-link">Messages</span><%= fa_icon 'paper-plane' %>
  <% end %>
</li>      
<li>
  <%= link_to concierge_path, id: 'sidebar-concierge-link' do %>
    <span class="nav-text-link">Concierge</span><%= fa_icon 'bell' %>
  <% end %>
</li>  
<li>
  <%= link_to concierge_path, id: 'sidebar-settings-link' do %>
    <span class="nav-text-link">Settings</span><%= fa_icon 'gear' %>
  <% end %>
</li>       

app/views/layouts/_mobile_header.html.erb
<div class="mobile-header" ng-controller="NavigationController as nav">
  <div class="top-bit">
    <div class="menu-toggle" ng-click="nav.toggle()" ng-class="{selected: nav.opened}"><%= fa_icon "bars" %></div>
    <h1>Kinected</h1>
  </div>
  <nav ng-class="{selected: nav.opened}">
    <ul>
      <%= render partial: 'layouts/nav_links_dater', locals: { mobile: true } %>
    </ul>
  </nav>
</div>

app/views/layouts/_nav_links_admin.html.erb
<li>
  <%= link_to admin_daters_path, id: 'sidebar-browse-link' do %>
    <span class="nav-text-link">Daters</span><%= fa_icon 'users' %>
  <% end %>
</li> 
<li>
  <%= link_to admin_daters_path, id: 'sidebar-concierge-link' do %>
    <span class="nav-text-link">Concierges</span><%= fa_icon 'bell' %>
  <% end %>
</li>  

app/views/layouts/_nav_links_dater.html.erb
<li class="<%= "selected" if current_page?(controller: 'daters', action: 'index') || (params[:action] == 'show' && params['controller'] == 'daters') %>">
  <%= link_to daters_path, id: "#{"mobile-" if mobile}sidebar-browse-link" do %>
    <span class="nav-text-link">Browse</span><%= fa_icon "users" %>
  <% end %>
</li>
<li class="<%= "selected" if current_page?(controller: 'messages', action: 'index') %>">
  <%= link_to messages_path, id: "#{"mobile-" if mobile}sidebar-messages-link" do %>
    <% if true %>
      <span class="unread"></span>
    <% end %>
    <span class="nav-text-link">Messages</span><%= fa_icon "paper-plane" %>
  <% end %>
</li>      
<li class="<%= "selected" if current_page?(controller: 'concierges', action: 'show') %>">
  <%= link_to concierge_path, id: "#{"mobile-" if mobile}sidebar-concierge-link" do %>
    <span class="nav-text-link">Concierge</span><%= fa_icon "bell" %>
  <% end %>
</li>  
<li class="<%= "selected" if current_page?(controller: 'daters', action: 'edit', id: current_user.id) %>">
  <%= link_to edit_dater_path(current_user), id: "#{"mobile-" if mobile}sidebar-settings-link" do %>
    <span class="nav-text-link">Settings</span><%= fa_icon "gear" %>
  <% end %>
</li>       

app/views/layouts/_sidebar_admin.html.erb
<aside>
  <header>
    <h1><a href="/">K<span class="hidden-in-mobile">inected</span></a></h1>
  </header>

    
  <nav>
    <ul>
      <%= render partial: 'layouts/nav_links_admin' %>
    </ul>
  </nav>
  
</aside>

app/views/layouts/_update_seen_count.html.erb
<div ng-controller="OnlineController as online" 
  data-user-id="<%= current_user.id %>" 
  data-display-name="<%= current_user.display_name%>" 
  data-current-time="<%= Time.now.to_i * 1000 %>" 
  data-thumb="<%= current_user.primary_profile_photo_thumb %>" 
  data-chatting-with="<%= get_chatting_partner_id %>">
  
</div>

app/views/layouts/application_admin.html.erb
<!DOCTYPE html>
<html ng-app="kinected">
<head>
  <title>Kinected</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
<!--   <link href='http://fonts.googleapis.com/css?family=Lato|Raleway:700' rel='stylesheet' type='text/css'>
 -->
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper with-sidebar">

  <%= render partial: 'layouts/sidebar_admin' %>

  <section>
    <%= render partial: 'layouts/flash_messages' %>


    <%= yield %>
    

    <%= render partial: 'layouts/footer' %>
    
  </section>
</div>
<!-- Render this partial everywhere on signed-in pages. -->
<%= render partial: 'layouts/update_seen_count' %>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/application_chat.html.erb
<!DOCTYPE html>
<html ng-app="kinected">
<head>
  <title>Kinected</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Lato|Raleway:700' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper with-sidebar">

  <%= render partial: 'layouts/mobile_header' %>

  <%= render partial: 'layouts/sidebar' %>

  <section class="chat-section">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


    <%= yield %>
    
    
  </section>
</div>
<!-- Render this partial everywhere on signed-in pages. -->
<%= render partial: 'layouts/update_seen_count' %>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/narrow_side_page.html.erb
<!DOCTYPE html>
<html ng-app="kinected">
<head>
  <title>Kinected</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body class="narrow-body">

  <%= yield %>
  <%= javascript_include_tag 'application' %>
</body>

</html>

app/views/layouts/onboarding.html.erb
<!DOCTYPE html>
<html ng-app="kinected">
<head>
  <title>Kinected</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="onboarding_body">

  <%= yield %>

</body>
</html>